import re

commaDights = re.compile(r'^\d{1,3}(,\d{3})*$')
mo = commaDights.search('42')
print(mo.group())
mo = commaDights.search('1,234')
print(mo.group())
mo = commaDights.search('6,368,745')
print(mo.group())

nameMatch = re.compile(r'[A-Z][a-z]*\sNakamoto')
mo = nameMatch.search('Satoshi Nakamoto')
print(mo.group())
mo = nameMatch.search('Alice Nakamoto')
print(mo.group())
mo = nameMatch.search('Robocop Nakamoto')
print(mo.group())

sentenceMatch = re.compile(r'(Alice|Bob|Carol)\s(eats|pets|throws)\s(apples|cats|baseballs)\.', re.I)
mo = sentenceMatch.search('Alice eats apples.')
print(mo.group())
mo = sentenceMatch.search('Bob pets cats.')
print(mo.group())
mo = sentenceMatch.search('Carol throws baseballs.')
print(mo.group())
mo = sentenceMatch.search('Alice throws Apples.')
print(mo.group())
mo = sentenceMatch.search('BOB EATS CATS.')
print(mo.group())
